#!/usr/bin/env bash
# METER: 서버 홈(또는 상위)의 통합 .env.production에서 값을 읽어
# backend / frontend 빌드·런타임용 env 파일을 생성합니다.
#
# 사용 (meter 디렉터리에서):
#   chmod +x scripts/prepare-env.sh
#   ./scripts/prepare-env.sh
#   ./scripts/prepare-env.sh ../.env.production
#
# 로컬 백엔드에서 dev 전용 유저(dev-local-meter)를 DB에 넣으려면 실행 전에:
#   export METER_DEV_USER_ENABLED=true

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ -n "${1:-}" ]]; then
  ROOT_ENV="$1"
else
  ROOT_ENV="$PROJECT_ROOT/../.env.production"
fi

if [[ ! -f "$ROOT_ENV" ]]; then
  echo "prepare-env: env 파일을 찾을 수 없습니다: $ROOT_ENV"
  echo "  (meter 폴더에서 ./scripts/prepare-env.sh ../.env.production 형태로 실행했는지 확인하세요)"
  exit 1
fi

ROOT_ENV="$(cd "$(dirname "$ROOT_ENV")" && pwd)/$(basename "$ROOT_ENV")"

set -a
# shellcheck disable=SC1090
source "$ROOT_ENV"
set +a

: "${GOOGLE_CLIENT_ID_METER:?prepare-env: GOOGLE_CLIENT_ID_METER 가 $ROOT_ENV 에 없습니다}"
: "${METER_GEMINI_API_KEY:?prepare-env: METER_GEMINI_API_KEY 가 $ROOT_ENV 에 없습니다}"
: "${DB_PASSWORD:?prepare-env: DB_PASSWORD 가 $ROOT_ENV 에 없습니다}"
: "${KAKAO_API_METER:?prepare-env: KAKAO_API_METER 가 $ROOT_ENV 에 없습니다}"

DB_USERNAME="${DB_USERNAME:-gwon}"
MQTT_BROKER_URL="${MQTT_BROKER_URL:-tcp://mosquitto:1883}"
MQTT_CLIENT_ID="${MQTT_CLIENT_ID:-meter-backend}"
VITE_API_BASE_URL="${VITE_API_BASE_URL:-/api}"
GEMINI_MODELS="${GEMINI_MODELS:-gemini-2.5-flash,gemini-2.5-flash-lite}"

umask 077

cat > "$PROJECT_ROOT/backend/.env.production" <<EOF
# generated by scripts/prepare-env.sh — do not commit
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_METER}
GEMINI_API_KEY=${METER_GEMINI_API_KEY}
GEMINI_MODELS=${GEMINI_MODELS}
MQTT_BROKER_URL=${MQTT_BROKER_URL}
MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
EOF

cat > "$PROJECT_ROOT/frontend/.env.production" <<EOF
# generated by scripts/prepare-env.sh — do not commit
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_METER}
VITE_API_BASE_URL=${VITE_API_BASE_URL}
VITE_KAKAO_API=${KAKAO_API_METER}
EOF

chmod 600 "$PROJECT_ROOT/backend/.env.production" "$PROJECT_ROOT/frontend/.env.production" 2>/dev/null || true

echo "prepare-env: OK"
echo "  backend:  $PROJECT_ROOT/backend/.env.production"
echo "  frontend: $PROJECT_ROOT/frontend/.env.production"
echo "  source:   $ROOT_ENV"
