#!/usr/bin/env bash
# METER: 서버 홈(또는 상위)의 통합 .env.production에서 값을 읽어
# backend / frontend 빌드·런타임용 env 파일을 생성합니다.
#
# 사용 (meter 디렉터리에서):
#   chmod +x scripts/prepare-env.sh
#   ./scripts/prepare-env.sh ../.env.production
#   docker compose up --build -d

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ -n "${1:-}" ]]; then
  ROOT_ENV="$1"
else
  ROOT_ENV="$PROJECT_ROOT/../.env.production"
fi

if [[ ! -f "$ROOT_ENV" ]]; then
  echo "prepare-env: env 파일을 찾을 수 없습니다: $ROOT_ENV"
  exit 1
fi

ROOT_ENV="$(cd "$(dirname "$ROOT_ENV")" && pwd)/$(basename "$ROOT_ENV")"

set -a
# shellcheck disable=SC1090
source "$ROOT_ENV"
set +a

# METER 키 우선, 없으면 GREENEYE/공통 키로 폴백 (서버 .env 마이그레이션용)
GOOGLE_CLIENT_ID_METER="${GOOGLE_CLIENT_ID_METER:-${GOOGLE_CLIENT_ID_GREENEYE:-}}"
METER_GEMINI_API_KEY="${METER_GEMINI_API_KEY:-${GREENEYE_GEMINI_API_KEY:-}}"
KAKAO_API_METER="${KAKAO_API_METER:-${KAKAO_API:-}}"

: "${GOOGLE_CLIENT_ID_METER:?prepare-env: GOOGLE_CLIENT_ID_METER (또는 GOOGLE_CLIENT_ID_GREENEYE) 가 $ROOT_ENV 에 없습니다}"
: "${METER_GEMINI_API_KEY:?prepare-env: METER_GEMINI_API_KEY (또는 GREENEYE_GEMINI_API_KEY) 가 $ROOT_ENV 에 없습니다}"
: "${DB_PASSWORD:?prepare-env: DB_PASSWORD 가 $ROOT_ENV 에 없습니다}"
: "${KAKAO_API_METER:?prepare-env: KAKAO_API_METER (또는 KAKAO_API) 가 $ROOT_ENV 에 없습니다}"

DB_USERNAME="${DB_USERNAME:-gwon}"
# meter-mosquitto 컨테이너 고정 (tcp://mosquitto 는 global_network 에 다른 브로커가 있으면 수신 0건)
MQTT_BROKER_URL="${MQTT_BROKER_URL:-tcp://meter-mosquitto:1883}"
MQTT_CLIENT_ID="${MQTT_CLIENT_ID:-meter-backend}"
VITE_API_BASE_URL="${VITE_API_BASE_URL:-/api}"
GEMINI_MODELS="${GEMINI_MODELS:-gemini-2.5-flash,gemini-2.5-flash-lite}"

# IoT 디바이스(모듈2 등) 전용 토큰 — 없으면 /api/device/** 가 503 으로 차단된다.
METER_DEVICE_TOKEN="${METER_DEVICE_TOKEN:-}"
if [[ -z "$METER_DEVICE_TOKEN" ]]; then
  echo "prepare-env: 경고 — METER_DEVICE_TOKEN 미설정. /api/device/** 는 차단됩니다."
  echo "             생성: openssl rand -hex 32"
fi

umask 077

cat > "$PROJECT_ROOT/backend/.env.production" <<EOF
# generated by scripts/prepare-env.sh — do not commit
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_METER}
GEMINI_API_KEY=${METER_GEMINI_API_KEY}
GEMINI_MODELS=${GEMINI_MODELS}
MQTT_BROKER_URL=${MQTT_BROKER_URL}
MQTT_CLIENT_ID=${MQTT_CLIENT_ID}
METER_DEVICE_TOKEN=${METER_DEVICE_TOKEN}
EOF

cat > "$PROJECT_ROOT/frontend/.env.production" <<EOF
# generated by scripts/prepare-env.sh — do not commit
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_METER}
VITE_API_BASE_URL=${VITE_API_BASE_URL}
VITE_KAKAO_API=${KAKAO_API_METER}
EOF

# docker compose build arg 치환용 (프로젝트 루트 .env)
cat > "$PROJECT_ROOT/.env" <<EOF
# generated by scripts/prepare-env.sh — do not commit
VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID_METER}
VITE_KAKAO_API=${KAKAO_API_METER}
VITE_API_BASE_URL=${VITE_API_BASE_URL}
EOF

chmod 600 "$PROJECT_ROOT/backend/.env.production" "$PROJECT_ROOT/frontend/.env.production" "$PROJECT_ROOT/.env" 2>/dev/null || true

echo "prepare-env: OK"
echo "  backend:  $PROJECT_ROOT/backend/.env.production"
echo "  frontend: $PROJECT_ROOT/frontend/.env.production"
echo "  compose:  $PROJECT_ROOT/.env"
echo "  source:   $ROOT_ENV"
